### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by Rob1NN** [turndj/tracker#3]
Where's the core repository?

**Comment by SEAPUNK** [comment]
The code is private. If you want to contribute to the code, you have to be invited into our team.

**Comment by Rob1NN** [comment]
So how does one get invited to that team?

**Comment by SEAPUNK** [comment]
They request via email.

They can email me at ivan@sq10.net.

**Comment by Rob1NN** [comment]
So wherefore doeth thou createth public reposit'rys if thy code is private and belike not yea thither yet
